
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EMPEZONAVIDAD = 5;
  public static final int STRING_LITERAL = 4;
  public static final int POLO = 42;
  public static final int DONNER = 28;
  public static final int SANNICOLAS = 52;
  public static final int l_SANTA = 10;
  public static final int FINREGALO = 49;
  public static final int l_PASCUERO = 13;
  public static final int HADA = 31;
  public static final int CIERRACUENTO = 44;
  public static final int PERSONA = 9;
  public static final int l_COLACHO = 14;
  public static final int DUENDE = 32;
  public static final int CIERRAREGALO = 48;
  public static final int ENTREGA = 15;
  public static final int VIEJITOPASCUERO = 54;
  public static final int ABREEMPAQUE = 45;
  public static final int RODOLFO = 24;
  public static final int CIERRAEMPAQUE = 46;
  public static final int ENTREGAREGALOS = 56;
  public static final int l_SANTA_CLAUS = 11;
  public static final int NAVIDAD = 6;
  public static final int INTEGER_INTEGRAL = 3;
  public static final int l_PAPANOEL = 12;
  public static final int NARRA = 58;
  public static final int HACE = 35;
  public static final int ENVUELVE = 33;
  public static final int PAPANOEL = 51;
  public static final int COMETA = 25;
  public static final int GRINCH = 22;
  public static final int FESTIVAL = 7;
  public static final int EOF = 0;
  public static final int SANTACLAUS = 50;
  public static final int CORTA = 38;
  public static final int MELCHOR = 39;
  public static final int REVISA = 36;
  public static final int error = 1;
  public static final int BALTASAR = 41;
  public static final int ABRECUENTO = 43;
  public static final int GASPAR = 40;
  public static final int ESCUCHA = 59;
  public static final int ABREREGALO = 47;
  public static final int DASHER = 29;
  public static final int CUPIDO = 27;
  public static final int ENVIA = 37;
  public static final int COLACHO = 55;
  public static final int BAILARIN = 26;
  public static final int FIESTA = 8;
  public static final int MUERDAGO = 57;
  public static final int SANTACLAUSULA = 60;
  public static final int ELFO = 30;
  public static final int ELFO6 = 21;
  public static final int ENVOLTURA = 34;
  public static final int ELFO5 = 20;
  public static final int ELFO4 = 19;
  public static final int ELFO3 = 18;
  public static final int SINTERKLASS = 53;
  public static final int ELFO2 = 17;
  public static final int ELFO1 = 16;
  public static final int QUIEN = 23;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "INTEGER_INTEGRAL",
  "STRING_LITERAL",
  "EMPEZONAVIDAD",
  "NAVIDAD",
  "FESTIVAL",
  "FIESTA",
  "PERSONA",
  "l_SANTA",
  "l_SANTA_CLAUS",
  "l_PAPANOEL",
  "l_PASCUERO",
  "l_COLACHO",
  "ENTREGA",
  "ELFO1",
  "ELFO2",
  "ELFO3",
  "ELFO4",
  "ELFO5",
  "ELFO6",
  "GRINCH",
  "QUIEN",
  "RODOLFO",
  "COMETA",
  "BAILARIN",
  "CUPIDO",
  "DONNER",
  "DASHER",
  "ELFO",
  "HADA",
  "DUENDE",
  "ENVUELVE",
  "ENVOLTURA",
  "HACE",
  "REVISA",
  "ENVIA",
  "CORTA",
  "MELCHOR",
  "GASPAR",
  "BALTASAR",
  "POLO",
  "ABRECUENTO",
  "CIERRACUENTO",
  "ABREEMPAQUE",
  "CIERRAEMPAQUE",
  "ABREREGALO",
  "CIERRAREGALO",
  "FINREGALO",
  "SANTACLAUS",
  "PAPANOEL",
  "SANNICOLAS",
  "SINTERKLASS",
  "VIEJITOPASCUERO",
  "COLACHO",
  "ENTREGAREGALOS",
  "MUERDAGO",
  "NARRA",
  "ESCUCHA",
  "SANTACLAUSULA"
  };
}

